### ISSUE TITLE
支持修改演员信息为中文

### ISSUE THREAD

**Issue by VectorZhao** [x1ao4/plex-localization-zh#2]
不知道能否实现这个功能。

**Comment by x1ao4** [comment]
首先，[TMDB](https://www.themoviedb.org/) 已经支持中文演员名（演职人员名）了，在 Plex 内直接使用 `The Movie Database` 代理进行刮削也可以直接获取中文演员名。但是 `The Movie Database` 这个代理在未来（估计不久）就会被 Plex 删除。

通过代码可以实现自行汉化演员名，但是目前可实现的方式是替换演员标签，替换后就变成本地标签了，而且还会失去演员的头像等信息，并且需要通过一个数据库来映射人名，那么就需要使用 API 来实现，如果用 TMDB 可能需要用户自己提供 API（TMDB 的 API 是免费的），豆瓣之类的又不提供 API。

总之就是，如果要从第三方实现是可以实现的，但是存在很多弊端，所以我应该不会考虑这个功能。与其由第三方实现，不如去催促 Plex 给他的新代理补上这个功能，因为这是一个 TMDB 已经实现了的功能，Plex 按理只需要通过这个接口获取翻译后的人名即可，因为老代理已经有这个功能了，但是新代理却没有，这十分不合理。

建议你去[这里](https://forums.plex.tv/t/support-for-translated-versions-of-actor-cast-names-and-biographies/879025)投票、评论。请求 Plex 官方支持刮削翻译后的人名和简介等信息。这是最好的方式。

如果你想通过第三方实现，目前已经有一些方式可以实现了，比如 [PrettyServer](https://github.com/Bespertrijun/PrettyServer)，MoviePilot 和 MovieBot 之类的也有类似的插件，比如 [MoviePilot-Plugins](https://github.com/InfinityPacer/MoviePilot-Plugins/)。（这些工具可以在保持头像的同时使用中文名，但同样也会失去演员的发现页面）

当然我必须要提醒你的是，目前第三方的实现方式都是替换标签，会损失一些信息（比如会无法使用演员的发现页面），也可能会出现一些其他问题，建议还是等 Plex 自己支持这个功能。

**Comment by VectorZhao** [comment]
感谢回复，我去向官方反馈。

**Comment by VectorZhao** [comment]
再问一下， PrettyServer前天跑了一遍，导致了你上面说的那些问题。请问如何恢复呢。演员发现界面已经不显示媒体库存在的电影和电视剧了。知名作品点进去，就算影视库存在该影片，也会提示本地媒体库没有。

**Comment by x1ao4** [comment]
PrettyServer 我本人并没有使用过，所以具体的处理方式不太清楚，建议你在 PrettyServer 的 Issues 中搜索一下，看看有没有类似的情况，或者去那里提交 Issue。

**Comment by VectorZhao** [comment]
谢谢
