### ISSUE TITLE
大佬，python报错请问怎么解决啊？感谢！

### ISSUE THREAD

**Issue by philboycn** [x1ao4/plex-localization-zh#3]
报错信息：
[root@CentOS plexlocalization]# python3 chinese-localization-for-plex.py --all
  File "chinese-localization-for-plex.py", line 223
    if new_genre := TAGS.get(genre):
                  ^
SyntaxError: invalid syntax

先谢谢大佬！

**Comment by x1ao4** [comment]
你是不是自己修改了 `tags.json` 文件里面的标签映射？

**Comment by philboycn** [comment]
没有修改过。但之前安装过MoviePilot并使用过里面的插件，是这个原因吗？应该怎么还原呢？

**Comment by x1ao4** [comment]
我建议你直接用 Docker 版。

**Comment by philboycn** [comment]
python升级到和docker同版本的3.8.19解决了，谢谢大佬！
